// frontend-vue/src/components/Header.vue
<script setup>
  import profileImage from "../images/default_profile.png"
  import coursesForHeader from "../views/courses/CourseHeaderView.vue"
  import tokenService from "../services/token.service.js"
</script>
<template>
  <nav class="mainNav">
    <ul>

      <li class="floatLeft">
        <router-link :to="{ name: 'Home' }" class='mainLink' >Home</router-link>
      </li>

      <li class="floatLeft">
        <div class="subnav">
          <router-link :to="{ name: 'Courses' }" class='mainLink'>Courses</router-link>
          <div className="subnavContent">
            <h2>Search for courses</h2>
            <input
              className="inputField"
              type="text"
              placeholder="Search.."
            />
            <table className="subnavTable">
              <!-- Following must be translated from React to Vue -->

              <thead>
                <tr>
                  <th>Course</th>
                  <th>Short Description</th>
                </tr>
              </thead>
              <tbody>

                  <coursesForHeader></coursesForHeader>

              </tbody>

            </table>
          </div>
        </div>
      </li>

      <li class="floatLeft">
        <router-link :to="{ name: 'About' }" class='mainLink'>About</router-link>
      </li>

      <li class="floatLeft">
        <router-link :to="{ name: 'AdminView' }" class='mainLink'>Admin Pages</router-link>
      </li>

      <li class="floatRight">
      <router-link v-if="!loggedIn" :to="{ name: 'Register' }" class='mainLink'>Register </router-link>
      </li>

      <li class="floatRight">
        <router-link v-if="loggedIn" @click="logOut" :to="{ name: 'Home' }" class='mainLink'>Log out</router-link> <!--should also log out a person and only visible to inlogged person-->
        <router-link v-else :to="{ name: 'Login' }" class='mainLink'>Log in</router-link>
      </li>

      <li class="floatRight">
      <router-link v-if="loggedIn" :to="{ name: 'Profile' }" class='mainLink profileImageLink'>
        <div className="headerProfileImageContainer">
          <img :src="profileImage" alt="Profile" />
        </div>
      </router-link>
      </li>
    </ul>
      
  </nav>
</template>

<script>
  export default{
    name:'Header',
    components: {
      coursesForHeader
    }, 
    computed: {
      loggedIn(){        
        console.log(this.$store.state.auth.user)
        return this.$store.state.auth.user
      },
    },
    methods: {
      logOut(user) {
        this.$store.dispatch("auth/logout", user).then(
        () => {

        },
        (error) => {
          this.loading = false;
          this.message =
            (error.response &&
              error.response.data &&
              error.response.data.message) ||
            error.message ||
            error.toString();
        }
      );
        // this.$store.dispatch("auth/logout").then(
        //   () => {
        //     this.$router.push({ name: 'Home'});
        //   },
        //   (error) => {
        //     this.loading = false;
        //     this.message =
        //       (error.response &&
        //         error.response.data &&
        //         error.response.data.message) ||
        //       error.message ||
        //       error.toString();
        //   }
        // )
      }
    },
    data() {
      return {
        
      }
    },
  }
</script>

// frontend-react/src/components/Header.js
import React from "react";
import { Link } from "react-router-dom";

import profileImage from "../images/default_profile.png";

const Header = () => {
  return (
    <nav className="mainNav">
      <ul>
        <li className="floatLeft">
          <Link className="mainLink" to="/">
            Home
          </Link>
        </li>

        <li className="floatLeft">
          <div className="subnav">
            <Link className="mainLink" to="/course">
              Courses
            </Link>
            <div class="subnavContent">
              <h2>Search for courses</h2>
              <input
                className="inputField"
                type="text"
                placeholder="Search.."
              />
              <table className="subnavTable">
                <tr>
                  <th>Course</th>
                  <th>Short Description</th>
                </tr>
                {[...Array(3)].map((e, i) => {
                  return (
                    <tr>
                      <td>
                        <Link to={`/course/${i + 1}`}>Course {i + 1}</Link>
                      </td>
                      <td>Course short description!</td>
                    </tr>
                  );
                })}
              </table>
            </div>
          </div>
        </li>

        <li className="floatLeft">
          <Link className="mainLink" to="/about">
            About
          </Link>
        </li>

        <li className="floatLeft">
          <Link className="mainLink" to="/admin">
            Admin pages
          </Link>
        </li>

        <li className="floatRight">
          <Link className="mainLink" to="/register">
            Register
          </Link>
        </li>

        <li className="floatRight">
          <Link className="mainLink" to="/login">
            Log in
          </Link>
        </li>

        <li>
          <Link className="mainLink profileImageLink floatRight" to="/profile">
            <div className="headerProfileImageContainer">
              <img src={profileImage} alt="Profile" />
            </div>
          </Link>
        </li>

        <li className="floatRight">
          <Link className="mainLink" to="/">
            Log out
          </Link>
        </li>
      </ul>
    </nav>
  );
};

export default Header;
